services:
  app:
    container_name: frontend-capture-live
    image: bartek2k/capture-live-frontend:latest
    environment:
      VITE_APP_API_URL: 'https://api.bartlomiejcisek.online'
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-capture-live.rule=Host(`bartlomiejcisek.online`)
      - traefik.http.routers.app-capture-live.entrypoints=web
      - traefik.http.routers.app-capture-live-https.tls=true
      - traefik.http.routers.app-capture-live-https.tls.certresolver=cloudflare
      - traefik.http.routers.app-capture-live-https.entrypoints=websecure
      - traefik.http.routers.app-capture-live-https.rule=Host(`bartlomiejcisek.online`)
    networks:
      - traefik

networks:
  traefik:
    external: true
