services:
  app:
    container_name: frontend-capture-live
    image: bartek2k/capture-live-frontend:latest
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-capture-live.rule=Host(`${VITE_APP_DOMAIN}`)
      - traefik.http.routers.frontend-capture-live.entrypoints=web
    networks:
      - traefik

networks:
  traefik:
    external: true
